package com.classvoice.dao;
import com.classvoice.model.*; import com.classvoice.util.DBConnection; import java.sql.*; import java.util.*;
public class FeedbackDAO {
 public long create(Feedback f)throws SQLException{String s="INSERT INTO feedback(lecture_id,student_id,topic_id,feedback_text) VALUES(?,?,?,?)";try(Connection c=DBConnection.getConnection();PreparedStatement p=c.prepareStatement(s,Statement.RETURN_GENERATED_KEYS)){p.setLong(1,f.getLectureId());p.setLong(2,f.getStudentId());if(f.getTopicId()==null)p.setNull(3,Types.BIGINT);else p.setLong(3,f.getTopicId());p.setString(4,f.getFeedbackText());p.executeUpdate();try(ResultSet r=p.getGeneratedKeys()){if(r.next())return r.getLong(1);}}return -1;}
 public int countForLecture(long lectureId)throws SQLException{return count("SELECT COUNT(*) FROM feedback WHERE lecture_id=?",lectureId);}
 public List<TopicStats> stats(long lectureId)throws SQLException{int total=countForLecture(lectureId);String s="SELECT t.topic_id,t.topic_name,COUNT(f.feedback_id) cnt FROM topics t LEFT JOIN feedback f ON f.topic_id=t.topic_id AND f.lecture_id=? WHERE t.lecture_id=? GROUP BY t.topic_id,t.topic_name ORDER BY cnt DESC,t.topic_id";List<TopicStats> out=new ArrayList<>();try(Connection c=DBConnection.getConnection();PreparedStatement p=c.prepareStatement(s)){p.setLong(1,lectureId);p.setLong(2,lectureId);try(ResultSet r=p.executeQuery()){while(r.next()){int n=r.getInt("cnt");out.add(new TopicStats(r.getLong("topic_id"),r.getString("topic_name"),n,total==0?0:(n*100.0/total)));}}}int other=count("SELECT COUNT(*) FROM feedback WHERE lecture_id=? AND topic_id IS NULL",lectureId);if(other>0)out.add(new TopicStats(-1,"Other / Uncategorized",other,total==0?0:(other*100.0/total)));return out;}
 public List<Feedback> findByLecture(long lectureId)throws SQLException{String s="SELECT f.*,t.topic_name,l.title lecture_title FROM feedback f LEFT JOIN topics t ON t.topic_id=f.topic_id JOIN lectures l ON l.lecture_id=f.lecture_id WHERE f.lecture_id=? ORDER BY f.submitted_at DESC";List<Feedback> out=new ArrayList<>();try(Connection c=DBConnection.getConnection();PreparedStatement p=c.prepareStatement(s)){p.setLong(1,lectureId);try(ResultSet r=p.executeQuery()){while(r.next()){Feedback f=new Feedback();f.setFeedbackId(r.getLong("feedback_id"));f.setLectureId(lectureId);f.setStudentId(r.getLong("student_id"));long tid=r.getLong("topic_id");f.setTopicId(r.wasNull()?null:tid);f.setTopicName(r.getString("topic_name"));f.setLectureTitle(r.getString("lecture_title"));f.setFeedbackText(r.getString("feedback_text"));f.setSubmittedAt(r.getTimestamp("submitted_at").toLocalDateTime());out.add(f);}}}return out;}
 public List<Feedback> findByStudent(long studentId)throws SQLException{String s="SELECT f.*,t.topic_name,l.title lecture_title FROM feedback f LEFT JOIN topics t ON t.topic_id=f.topic_id JOIN lectures l ON l.lecture_id=f.lecture_id WHERE f.student_id=? ORDER BY f.submitted_at DESC";List<Feedback> out=new ArrayList<>();try(Connection c=DBConnection.getConnection();PreparedStatement p=c.prepareStatement(s)){p.setLong(1,studentId);try(ResultSet r=p.executeQuery()){while(r.next()){Feedback f=new Feedback();f.setFeedbackId(r.getLong("feedback_id"));f.setLectureId(r.getLong("lecture_id"));f.setStudentId(studentId);long tid=r.getLong("topic_id");f.setTopicId(r.wasNull()?null:tid);f.setTopicName(r.getString("topic_name"));f.setLectureTitle(r.getString("lecture_title"));f.setFeedbackText(r.getString("feedback_text"));f.setSubmittedAt(r.getTimestamp("submitted_at").toLocalDateTime());out.add(f);}}}return out;}
 private int count(String s,long id)throws SQLException{try(Connection c=DBConnection.getConnection();PreparedStatement p=c.prepareStatement(s)){p.setLong(1,id);try(ResultSet r=p.executeQuery()){r.next();return r.getInt(1);}}}
}
