package com.classvoice.dao;
import com.classvoice.model.Lecture; import com.classvoice.util.DBConnection; import java.sql.*; import java.util.*;
public class LectureDAO {
 public long create(Lecture l)throws SQLException{String s="INSERT INTO lectures(teacher_id,title,description,lecture_date,status) VALUES(?,?,?,?, 'inactive')";try(Connection c=DBConnection.getConnection();PreparedStatement p=c.prepareStatement(s,Statement.RETURN_GENERATED_KEYS)){p.setLong(1,l.getTeacherId());p.setString(2,l.getTitle());p.setString(3,l.getDescription());p.setDate(4,java.sql.Date.valueOf(l.getLectureDate()));p.executeUpdate();try(ResultSet r=p.getGeneratedKeys()){if(r.next())return r.getLong(1);}}return -1;}
 public Lecture findById(long id)throws SQLException{String s="SELECT l.*,u.name teacher_name,(SELECT COUNT(*) FROM topics t WHERE t.lecture_id=l.lecture_id) topic_count,(SELECT COUNT(*) FROM feedback f WHERE f.lecture_id=l.lecture_id) feedback_count FROM lectures l JOIN users u ON u.user_id=l.teacher_id WHERE l.lecture_id=?";try(Connection c=DBConnection.getConnection();PreparedStatement p=c.prepareStatement(s)){p.setLong(1,id);try(ResultSet r=p.executeQuery()){return r.next()?map(r):null;}}}
 public List<Lecture> findByTeacher(long teacherId)throws SQLException{String s="SELECT l.*,u.name teacher_name,(SELECT COUNT(*) FROM topics t WHERE t.lecture_id=l.lecture_id) topic_count,(SELECT COUNT(*) FROM feedback f WHERE f.lecture_id=l.lecture_id) feedback_count FROM lectures l JOIN users u ON u.user_id=l.teacher_id WHERE l.teacher_id=? ORDER BY l.lecture_date DESC,l.lecture_id DESC";return list(s,teacherId);}
 public List<Lecture> findActive()throws SQLException{String s="SELECT l.*,u.name teacher_name,(SELECT COUNT(*) FROM topics t WHERE t.lecture_id=l.lecture_id) topic_count,(SELECT COUNT(*) FROM feedback f WHERE f.lecture_id=l.lecture_id) feedback_count FROM lectures l JOIN users u ON u.user_id=l.teacher_id WHERE l.status='active' ORDER BY l.lecture_date DESC,l.lecture_id DESC";return list(s);}
 public boolean setStatus(long lectureId,long teacherId,String status)throws SQLException{String s="UPDATE lectures SET status=? WHERE lecture_id=? AND teacher_id=?";try(Connection c=DBConnection.getConnection();PreparedStatement p=c.prepareStatement(s)){p.setString(1,status);p.setLong(2,lectureId);p.setLong(3,teacherId);return p.executeUpdate()==1;}}
 public boolean belongsToTeacher(long lectureId,long teacherId)throws SQLException{String s="SELECT 1 FROM lectures WHERE lecture_id=? AND teacher_id=?";try(Connection c=DBConnection.getConnection();PreparedStatement p=c.prepareStatement(s)){p.setLong(1,lectureId);p.setLong(2,teacherId);try(ResultSet r=p.executeQuery()){return r.next();}}}
 public int countActive(long teacherId)throws SQLException{String s="SELECT COUNT(*) FROM lectures WHERE teacher_id=? AND status='active'";return count(s,teacherId);}
 public int countFeedback(long teacherId)throws SQLException{String s="SELECT COUNT(*) FROM feedback f JOIN lectures l ON l.lecture_id=f.lecture_id WHERE l.teacher_id=?";return count(s,teacherId);}
 private int count(String s,long id)throws SQLException{try(Connection c=DBConnection.getConnection();PreparedStatement p=c.prepareStatement(s)){p.setLong(1,id);try(ResultSet r=p.executeQuery()){r.next();return r.getInt(1);}}}
 private List<Lecture> list(String s,Object... args)throws SQLException{List<Lecture> out=new ArrayList<>();try(Connection c=DBConnection.getConnection();PreparedStatement p=c.prepareStatement(s)){for(int i=0;i<args.length;i++)p.setObject(i+1,args[i]);try(ResultSet r=p.executeQuery()){while(r.next())out.add(map(r));}}return out;}
 private Lecture map(ResultSet r)throws SQLException{Lecture l=new Lecture();l.setLectureId(r.getLong("lecture_id"));l.setTeacherId(r.getLong("teacher_id"));l.setTitle(r.getString("title"));l.setDescription(r.getString("description"));l.setLectureDate(r.getDate("lecture_date").toLocalDate());l.setStatus(r.getString("status"));l.setTeacherName(r.getString("teacher_name"));l.setTopicCount(r.getInt("topic_count"));l.setFeedbackCount(r.getInt("feedback_count"));return l;}
}
